
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA CONST_USE EQUALS LBRACE LPAREN NAME NUMBER RBRACE RPAREN SEMICOLONconfig : elementselements : element elements\n| elementelement : const_decl\n| dict\n| arrayconst_decl : NAME EQUALS value SEMICOLONdict : LBRACE pairs RBRACE\n| LBRACE RBRACEpairs : pair\n| pair COMMA pairspair : NAME COLON valuearray : LPAREN values RPAREN\n| LPAREN RPARENvalues : value\n| value COMMA valuesvalue : NUMBER\n| dict\n| array\n| CONST_USE'
    
_lr_action_items = {'NAME':([0,3,4,5,6,8,13,17,24,25,27,29,],[7,7,-4,-5,-6,15,-9,-14,-8,15,-13,-7,]),'LBRACE':([0,3,4,5,6,9,11,13,17,24,26,27,28,29,],[8,8,-4,-5,-6,8,8,-9,-14,-8,8,-13,8,-7,]),'LPAREN':([0,3,4,5,6,9,11,13,17,24,26,27,28,29,],[9,9,-4,-5,-6,9,9,-9,-14,-8,9,-13,9,-7,]),'$end':([1,2,3,4,5,6,10,13,17,24,27,29,],[0,-1,-3,-4,-5,-6,-2,-9,-14,-8,-13,-7,]),'EQUALS':([7,],[11,]),'RBRACE':([8,12,13,14,17,19,20,21,22,24,27,30,31,],[13,24,-9,-10,-14,-17,-18,-19,-20,-8,-13,-11,-12,]),'RPAREN':([9,13,16,17,18,19,20,21,22,24,27,32,],[17,-9,27,-14,-15,-17,-18,-19,-20,-8,-13,-16,]),'NUMBER':([9,11,26,28,],[19,19,19,19,]),'CONST_USE':([9,11,26,28,],[22,22,22,22,]),'COMMA':([13,14,17,18,19,20,21,22,24,27,31,],[-9,25,-14,28,-17,-18,-19,-20,-8,-13,-12,]),'SEMICOLON':([13,17,19,20,21,22,23,24,27,],[-9,-14,-17,-18,-19,-20,29,-8,-13,]),'COLON':([15,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'config':([0,],[1,]),'elements':([0,3,],[2,10,]),'element':([0,3,],[3,3,]),'const_decl':([0,3,],[4,4,]),'dict':([0,3,9,11,26,28,],[5,5,20,20,20,20,]),'array':([0,3,9,11,26,28,],[6,6,21,21,21,21,]),'pairs':([8,25,],[12,30,]),'pair':([8,25,],[14,14,]),'values':([9,28,],[16,32,]),'value':([9,11,26,28,],[18,23,31,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> config","S'",1,None,None,None),
  ('config -> elements','config',1,'p_config','parser.py',59),
  ('elements -> element elements','elements',2,'p_elements','parser.py',63),
  ('elements -> element','elements',1,'p_elements','parser.py',64),
  ('element -> const_decl','element',1,'p_element','parser.py',79),
  ('element -> dict','element',1,'p_element','parser.py',80),
  ('element -> array','element',1,'p_element','parser.py',81),
  ('const_decl -> NAME EQUALS value SEMICOLON','const_decl',4,'p_const_decl','parser.py',85),
  ('dict -> LBRACE pairs RBRACE','dict',3,'p_dict','parser.py',90),
  ('dict -> LBRACE RBRACE','dict',2,'p_dict','parser.py',91),
  ('pairs -> pair','pairs',1,'p_pairs','parser.py',98),
  ('pairs -> pair COMMA pairs','pairs',3,'p_pairs','parser.py',99),
  ('pair -> NAME COLON value','pair',3,'p_pair','parser.py',106),
  ('array -> LPAREN values RPAREN','array',3,'p_array','parser.py',110),
  ('array -> LPAREN RPAREN','array',2,'p_array','parser.py',111),
  ('values -> value','values',1,'p_values','parser.py',118),
  ('values -> value COMMA values','values',3,'p_values','parser.py',119),
  ('value -> NUMBER','value',1,'p_value','parser.py',126),
  ('value -> dict','value',1,'p_value','parser.py',127),
  ('value -> array','value',1,'p_value','parser.py',128),
  ('value -> CONST_USE','value',1,'p_value','parser.py',129),
]
